trophi_app.py

import streamlit as st
import pandas as pd

# --- CONFIGURATION ---
st.set_page_config(page_title="Trophi.ai Priority Engine", layout="centered")

# --- HEADER ---
st.title("🏎️ Trophi.ai Priority Engine")
st.markdown("""
**Prototype v0.1** | Built by David Battcock
*Objective: Quantify 'Opportunity Cost' for Inbound Partnerships & Expansions.*
""")
st.divider()

# --- SIDEBAR INPUTS ---
st.sidebar.header("Opportunity Details")
opp_name = st.sidebar.text_input("Project Name", "e.g., Counter-Strike 2 Integration")
opp_type = st.sidebar.selectbox("Type", ["New Game Integration", "Hardware Partnership", "Enterprise SDK", "Marketing Event"])

st.sidebar.subheader("Scoring Parameters")
# 1 = Low, 5 = High
tam_score = st.sidebar.slider("TAM / User Reach (1-5)", 1, 5, 4)
tech_lift = st.sidebar.slider("Engineering Lift (1=Easy, 5=Hard)", 1, 5, 5)
rev_potential = st.sidebar.slider("Immediate ARR Potential (1-5)", 1, 5, 2)
strat_fit = st.sidebar.slider("Strategic Moat Alignment (1-5)", 1, 5, 5)

# --- THE ALGORITHM ---
# This is the "Operator Logic" - The math behind the decision
def calculate_score(tam, lift, rev, strat):
    # Weighted Logic: Strategic Fit and Engineering Lift are heavily weighted
    score = (tam * 1.5) + (rev * 2.0) + (strat * 1.5) - (lift * 2.5)
    # Normalize to 0-100 scale roughly
    normalized_score = max(0, min(100, (score + 10) * 4)) 
    return round(normalized_score, 1)

final_score = calculate_score(tam_score, tech_lift, rev_potential, strat_fit)

# --- MAIN DASHBOARD ---
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader(f"Analysis: {opp_name}")
    if final_score >= 75:
        st.success(f"✅ **GREENLIGHT** (Score: {final_score})")
        st.write("Recommendation: Prioritize immediately. High ROI relative to engineering cost.")
    elif final_score >= 50:
        st.warning(f"⚠️ **EVALUATE** (Score: {final_score})")
        st.write("Recommendation: Move to Backlog. Requires scoping or more resources.")
    else:
        st.error(f"🛑 **KILL / DEFER** (Score: {final_score})")
        st.write("Recommendation: Opportunity Cost too high. Distraction risk.")

with col2:
    st.metric(label="Trophi Score", value=final_score)

# --- AI GENERATION PROTOTYPE ---
st.divider()
st.subheader("🤖 AI Decision Memo Generator")
st.caption("In the full version, this connects to OpenAI API to draft the memo automatically.")

if st.button("Generate Memo Draft"):
    st.text_area("Draft Output", height=200, value=f"""
TO: Executive Team
RE: Strategic Assessment of {opp_name}

EXECUTIVE SUMMARY:
This opportunity scored a {final_score}/100 on the Priority Engine. 

KEY DRIVERS:
- Technical Risk is rated {tech_lift}/5.
- Strategic Alignment is rated {strat_fit}/5.

RECOMMENDATION:
Based on the high engineering lift required vs. immediate revenue, the system recommends we DEFER this project to Q2 to protect the core roadmap.

Generated by Trophi Ops Bot
    """)
